function S = CreateBTMSliders(S)
    width = 500;
    textwidth = width;
    height = 40;
    spacingX = 1200;
    wY = 800;
    bAY = 700;
    mAY = 600;
    S.wLabel = uicontrol('Style','text','Position',[10+spacingX 10+wY+height textwidth height],'fontsize',20,'HorizontalAlignment','left');
    S.wSlider = uicontrol('style','slide',...
                 'unit','pixels', 'position',[spacingX wY width height],...
                 'min',0.001,'max',359.999,'value', S.w,...
                 'sliderstep',[1/360 1/72],...
                 'callback', {@SliderCB_BTM, 'w'});
    S.bALabel = uicontrol('Style','text','Position',[10+spacingX 10+bAY+height textwidth height],'fontsize',20,'HorizontalAlignment','left');
    S.bASlider = uicontrol('style','slide',...
                 'unit','pixels', 'position',[spacingX bAY width height],...
                 'min',0.001,'max',359.998,'value', S.bA,...
                 'sliderstep',[1/360 1/72],...
                 'callback', {@SliderCB_BTM, 'bA'});
    S.mALabel = uicontrol('Style','text','Position',[10+spacingX 10+mAY+height textwidth height],'fontsize',20,'HorizontalAlignment','left');
    S.mASlider = uicontrol('style','slide',...
                 'unit','pixels', 'position',[spacingX mAY width height],...
                 'min',0.001,'max',179.999,'value', S.mA,...
                 'sliderstep',[1/360 1/72],...
                 'callback', {@SliderCB_BTM, 'mA'});
end