function S = CreateW(S)
    width = 500;
    textwidth = width;
    height = 40;
    spacing = 60;
    S.wLabel = uicontrol('Style','text','Position',[10+spacing+width 120 textwidth height],'fontsize',20,'HorizontalAlignment','left');
    S.wSlider = uicontrol('style','slide',...
                 'unit','pixels', 'position',[spacing 120 width height],...
                 'min',0,'max',360,'value', S.w,...
                 'sliderstep',[0.01 0.01],...
                 'callback', {@SliderCB, 'w'});
end